### ISSUE TITLE
Upgrade to Django 1.7

### ISSUE THREAD

**Issue by osamak** [enjaz/enjaz#66]
Django 1.7 was finally just released. Ultimately, we will need to upgrade. The sub-tasks will include:
- Getting rid of South.
- Adopting the built-in migrations.
- Evaluating every single dependency for compatibility.
  - Userena, specifically,  will probably face issues sine AUTH_PROFILE_MODULE was removed.

Furthermore, we will need to evaluate the improvements brought by this release to see if/how they can serve the project.

**Comment by msarabi95** [comment]
This is an old issue. Enjaz is already running Django 1.8.
